### ISSUE TITLE
Fix Deployment issue

### ISSUE THREAD

**Issue by first-brick** [first-brick/landing-website#7]

**Comment by first-brick** [comment]
2020-10-08T18:37:50.430643+00:00 heroku[router]: at=info method=GET path="/" host=firstbrick.herokuapp.com request_id=0c4e39af-1a79-4ca9-ab3d-bf21fd50a584 fwd="49.37.1.0" dyno=web.1 connect=0ms service=5ms status=500 bytes=404 protocol=https

2020-10-08T18:37:50.431135+00:00 app[web.1]: ReferenceError: dbService is not defined

2020-10-08T18:37:50.431145+00:00 app[web.1]:     at /app/app.js:36:29

2020-10-08T18:37:50.431150+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

2020-10-08T18:37:50.431151+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

2020-10-08T18:37:50.431152+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7

2020-10-08T18:37:50.431153+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

2020-10-08T18:37:50.431153+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)

2020-10-08T18:37:50.431154+00:00 app[web.1]:     at module.exports (/app/node_modules/express-ejs-layouts/lib/express-layouts.js:116:3)

2020-10-08T18:37:50.431154+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

2020-10-08T18:37:50.431155+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

2020-10-08T18:37:50.431155+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7

**Comment by pradipta** [comment]
Related to https://github.com/first-brick/landing-website/issues/2

**Comment by first-brick** [comment]
Fixed
